# Generated by Django 3.1 on 2020-08-26 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.TextField(max_length=128)),
                ('brand', models.TextField(max_length=128)),
                ('status', models.TextField()),
                ('portfolio_size', models.IntegerField()),
                ('origin', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.BooleanField()),
                ('blocked_reason', models.TextField()),
            ],
        ),
    ]
