# Generated by Django 3.1 on 2020-08-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='blocked_reason',
            field=models.TextField(null=True),
        ),
    ]
